export interface TextLayer {value:string;fontFamily:string;fontSize:number;color:string;x:number;y:number}
export interface TextEffects {stroke?:{color:string;size:number};shadow?:{color:string;blur:number;offsetX:number;offsetY:number;opacity:number}}
export interface Layer {id:string;name:string;url:string;previewUrl?:string;x:number;y:number;width:number;height:number;visible:boolean;opacity:number;opinion:string;disposition:'keep'|'rebuild';kind:'raster'|'text'|'vector';svg?:string;text?:TextLayer;textDirty?:boolean;psdStyle?:TextEffects;role?:'background'|'foreground';preview?:boolean;originalPsdIndex?:number[];groupPath?:string[]}
export interface Annotation {id:string;layerId:string|null;type:'arrow'|'ellipse'|'box'|'pen'|'text';points:number[];text:string;color:string;brushSize?:number;opacity?:number;strokeWidth?:number;fontWeight?:number;fontSize?:number;labelPosition?:[number,number]}
export type VectorEngine='vectorizerCom'|'recraft'|'vectorizer302'|'vectorizer';
export interface VectorOptions {supersvg?:{pathNum?:number;refinePathsPerSegment?:number;refineBatchSize?:number;seed?:number;optimizeIter?:number;device?:'auto'|'cpu'|'cuda'};adavec?:{[key:string]:number|string|boolean}}
export interface CanvasImage {id:string;name:string;width:number;height:number;x:number;y:number;source:string;url:string;layers:Layer[];vectorLayers?:Layer[];annotations:Annotation[];opinion:string;status:'original'|'preview'|'layered'|'vector';version:number;vectorUrl?:string;psdSource?:string;parentId?:string;sourceJobId?:string;sourceVersion?:number;basedOnOlderVersion?:boolean;artifactUrl?:string}
export interface Document {id:string;taskId:string;revision:number;images:CanvasImage[];settings:{psdMode:2|3;vectorEngine:VectorEngine;vectorizerComMode?:'auto'|'codex';vectorOptions?:VectorOptions;theme:'dark'|'light'};layout:{layersWidth:number;opinionsWidth:number;editorHeight:number};updatedAt:string}
export interface Job {webProgress?:{phase:'working'|'verification'|'blocked';updatedAt:string;completed?:number;reviewUrl?:string;detail?:string};dispatch?:{state:"sending"|"sent"|"received"|"failed"|"uncertain";updatedAt:string;detail?:string};id:string;documentId:string;taskId:string;imageId:string;type:'plan'|'layer'|'revise'|'vectorize'|'photoshop'|'illustrator';status:'queued'|'running'|'waiting_codex'|'completed'|'failed'|'cancelled';message:string;createdAt:string;version:number;mode:1|2|3;engine:VectorEngine;webMode?:'auto'|'codex';vectorOptions?:VectorOptions;layerIds?:string[];useOriginal?:boolean;useVectorLayers?:boolean;snapshot:CanvasImage;result?:unknown}
