import {useEffect,useState} from 'react';
import {api,download} from './api';
export default function ExternalVector({jobId,onClose,onComplete}:{jobId:string;onClose:()=>void;onComplete:()=>void}){
 const [inputs,setInputs]=useState<{id:string;name:string;needsFile:boolean}[]>([]);
 const [files,setFiles]=useState<Record<string,File>>({});const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [loaded,setLoaded]=useState(false);
 useEffect(()=>{api<{inputs:typeof inputs}>(`/api/jobs/${jobId}/external-inputs`).then(r=>{setInputs(r.inputs);setLoaded(true)}).catch(e=>setError(String(e)))},[jobId]);
 const submit=async()=>{setBusy(true);setError('');try{const body=new FormData();for(const l of inputs.filter(l=>l.needsFile))body.append(l.id,files[l.id]);await api(`/api/jobs/${jobId}/external-complete`,{method:'POST',body});onComplete();}catch(e){setError(String(e))}finally{setBusy(false)}};
 return <div className="modal-backdrop"><section className="settings-modal"><div className="modal-heading"><h2>Vectorizer.com 免费网页转换</h2><button disabled={busy} onClick={onClose}>×</button></div><div className="settings-body"><p>下载以下原图或图层，在官网转换后，将对应 SVG 选回原来的图层。位置和顺序由画布保留；网页转换不会自动执行。</p><p><a href="https://vectorizer.com/" target="_blank" rel="noreferrer">打开 Vectorizer.com ↗</a></p><p className="settings-note">无需 API Key。官网未开放集成许可；此入口只导出和导入文件，不自动上传图片。关闭窗口后可从任务列表继续。</p>{inputs.map(l=><div className="external-layer" key={l.id}><b>{l.name}</b>{l.needsFile?<><button disabled={busy} onClick={()=>download(`/api/jobs/${jobId}/external-input/${encodeURIComponent(l.id)}`,`${l.name.replace(/[\\/:*?"<>|]/g,'_')}.png`).catch(e=>setError(String(e)))}>下载 PNG</button><label>选择对应 SVG<input disabled={busy} type="file" accept=".svg" onChange={e=>{const f=e.target.files?.[0];if(f)setFiles(old=>({...old,[l.id]:f}))}}/></label></>:<small>已有矢量 / 可编辑文字，将直接保留</small>}</div>)}{error&&<p role="alert">{error}</p>}<button className="primary" disabled={busy||!loaded||inputs.some(l=>l.needsFile&&!files[l.id])} onClick={submit}>{busy?'正在导回…':'导回并创建矢量节点'}</button></div></section></div>;
}
